[package]
name = "axochat"
version = "0.1.0"
authors = ["frozolotl <frozolotl@protonmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.9"
toml = "0.4"
